[package]
name = "aoc2015"
version = "0.1.0"
edition = "2021"
authors = ["peter@howell.fun"]

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
indoc = "2.0.4"
itertools = "0.13.0"
intersection = "1.0.0"
aoc = "0.6.1"
